# Generated by Django 5.0.9 on 2024-12-22 07:02

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0121_customfield_related_object_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('assigned_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('crit_ep_impacted', models.BooleanField(default=False)),
                ('impact_rating', models.CharField(default='OUTAGE', max_length=30)),
                ('bus_impact_assess', models.TextField(blank=True, default='')),
                ('tech_impact_assess', models.TextField(blank=True, default='')),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('assigned_object_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'device')), models.Q(('app_label', 'circuits'), ('model', 'circuit')), _connector='OR')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['assigned_object_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='impact',
            constraint=models.UniqueConstraint(models.F('assigned_object_type'), models.F('assigned_object_id'), name='netbox_opsmgmt_impact_unique_object', violation_error_message='Objects must be unique.'),
        ),
    ]
